version: '3'
services:
  app:
    build:
      context: .
      dockerfile: _Docker/Dockerfile
    image: dryft
    ports:
      - 80:80
    volumes:
      - .:/srv/app
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: dryft
      MYSQL_USER: dryft
      MYSQL_PASSWORD: ADeveloperPassword
      MYSQL_ROOT_PASSWORD: ADeepRootedPassword
    volumes:
      - ./_Docker/DatabaseBootstrap.sql:/docker-entrypoint-initdb.d/dryft.sql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
